#Update the module name for the DuT
MODULE=xc_aessub


VMODULE=V$(MODULE)
DUTPATH=../../eut/xcrypto/rtl/$(MODULE)/$(MODULE).v
DUTPATH+=../../eut/xcrypto/rtl/xc_aessub/xc_aessub_sbox.v
POWER_LIBS=../power_libs

include $(POWER_LIBS)/common.mk
