#Update the module name for the DuT
MODULE=riscv_crypto_fu_ssha256


VMODULE=V$(MODULE)
DUTPATH=../../eut/riscv-crypto/rtl/crypto-fu/$(MODULE).v
POWER_LIBS=../power_libs

include $(POWER_LIBS)/common.mk
