#!/usr/bin/env python3

import sys
import csv
import matplotlib.pyplot as plt

def plot_line_chart(csv_file):
    try:
        with open(csv_file, 'r') as file:
            reader = csv.reader(file)
            data = list(reader)
    except FileNotFoundError:
        print(f"Error: File '{csv_file}' not found.")
        sys.exit(1)
    except csv.Error:
        print(f"Error: Unable to parse data from '{csv_file}'. Make sure it's a valid CSV file.")
        sys.exit(1)

    # Check if the CSV file contains at least two columns
    if len(data[0]) < 2:
        print("Error: The CSV file must have at least two columns.")
        sys.exit(1)

    # Use row numbers as x-values
    x = list(range(1, len(data)))  # Exclude the header

    # Plot each  column as a separate line
    for i in range(0, len(data[0])):
        y = [float(row[i]) for row in data[1:]]  # Exclude the header
        plt.plot(x, y, label=data[0][i])

    # Use the title from the first column of the first row
    title = csv_file
    plt.title(title)
    title = data[0][0] if data[0][0] else 'Line Chart'
    plt.title(title)
    plt.xlabel('Cycles')
    plt.ylabel('Power')
    plt.legend()
    # plt.show()

    # Save the plot as an SVG file with the same name as the CSV file
    svg_filename = csv_file.replace('.csv', '.svg')
    plt.savefig(svg_filename, format='svg')

    print(f"Plot saved as {svg_filename}")

if __name__ == "__main__":
    # Check if a CSV file is provided as a command-line argument
    if len(sys.argv) != 2:
        print("Usage: python script.py <csv_file>")
        sys.exit(1)

    csv_file = sys.argv[1]
    plot_line_chart(csv_file)